// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    PageHead: typeof import('./src/components/pageHead/index.vue')['default']
    ShadowText: typeof import('./src/components/shadowText/index.vue')['default']
    SvgIcon: typeof import('./src/components/svgComp/SvgIcon.vue')['default']
    ToggleThemeSwitch: typeof import('./src/components/toggleThemeSwitch/index.vue')['default']
  }
}

export { }
