name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@master  
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4 
        with:  
          token: ${{ secrets.HOME_SECRETS }} 
          branch: main
          folder: dist
          repository-name: HXSlimeng/HXSlimeng.github.io 
          # TARGET_FOLDER: github-actions-demo 
